### PR TITLE
Improve parse_type UnknownImageType detection

### PR DESCRIPTION
**Pull request by Bertg**
In case of 'ice' a default value should raise `UnknownImageType` but it didn't, probably due to the code not being 100% DRY.

This commit fixes both issues at once

### CODE REVIEW

**Comment by schmidt** [comment]
Thanks a lot for the suggested changes and your effort.

And here's the but: I would prefer if you suggested the change to the upstream sdsykes/fastimage project, since I want this gem to be as close to the original as feasible. Also I think that version has a lot more users and this way your contribution reaches a wider audience.

Secondly I would like to avoid variables named `type`, since `type` is already defined on `Object` and this might lead so undesired side effects - especially if the variable is somehow defined in a different scope as it is used. This is not the case here. But it's the reason, why I always try to avoid that name.

~~And lastly, Travis does not seem to like your change.~~

**Comment by Bertg** [comment]
Yeah, I noticed. Thing is that we are using this version internally, and I noticed to upstream version has already pulled some of your changes in. 

I'm willing to push the same changes there as well, but I'd like to see these changes pushed with this gem (and the Tiff fixes ;) )
- [x] make Travis love this commit
- [x] Change variable `type` to something else

**Comment by schmidt** [comment]
Which tiff fixes?

**Comment by Bertg** [comment]
Oh, sorry. Forgot to not talk work context here :) .

Commit dc3bfda4b7f926e236777bcd44551ab0fd15bd20 fixes a lot of TIFF file related issues we have seen on our side. I noticed nor this fork, nor the original has released it, so I'm kind of exited to see it be released.

**Comment by schmidt** [comment]
Thanks for your contribution. I have squashed your commits and added an additional test. Everything will be released as v3.0.2 shortly.

**Pull request closed without merging**
